- app/src/main/java/com/example/circleapp/Attendee.java
Addinf stuff in attendee class
> adding stuff in attendee class

- app/src/main/java/com/example/circleapp/Attendee.java
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
> added to profile fragment

- app/src/main/res/layout/fragment_profile.xml
> changes input line colour

- app/src/main/res/layout/event_item.xml
> have a section for pictures for event list 

- app/src/main/java/com/example/circleapp/ProfileFragment.java
- app/src/main/res/layout/fragment_profile.xml
I commented it out cause theres a bug but I'll fix it later
> added attendee info to profile fragment class

- .idea/misc.xml
- app/src/main/java/com/example/circleapp/ProfileFragment.java
- app/src/main/java/com/example/circleapp/ScanQRActivity.java
- app/src/main/java/com/example/circleapp/YourEventsFragment.java
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/fragment_your_events.xml
Moved Scan QR button to YourEventsFragment. Fixed issue where ScanQRctivity was being launched twice when button was pressed.
> Relocate Scan QR button and bug fixes

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/circleapp/EventDetailsActivity.java
- app/src/main/java/com/example/circleapp/GenerateQRActivity.java
- app/src/main/res/layout/activity_generate_qr.xml
- app/src/main/res/layout/event_details_activity.xml
- app/src/main/res/layout/scan_qr.xml
- app/src/main/res/values/strings.xml
Added functionality to generate QR code from event details page. Still have to add event details to QR code.
> TAKE 2: Generate QR code

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/circleapp/GenerateQRActivity.java
- app/src/main/res/layout/activity_generate_qr.xml
- app/src/main/res/xml/file_path.xml
Added functionality to share QR code, after it is generated.
> Share QR code

- app/src/main/java/com/example/circleapp/Event.java
- app/src/main/java/com/example/circleapp/GenerateQRActivity.java
eventID can be used to link to event details in firebase
> Generated QR code now contains eventID

- app/src/main/java/com/example/circleapp/BaseObjects/Event.java
- app/src/main/java/com/example/circleapp/EventDisplay/BrowseEventsFragment.java
- app/src/main/java/com/example/circleapp/FirebaseManager.java
Fixed bug where events are not displayed from Firestore.
> Firestore Bug

- app/src/main/AndroidManifest.xml
Scanner is now in portrait orientation
> QR Scanner Orientation

- app/src/main/java/com/example/circleapp/EventDisplay/EventDetailsActivity.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/values/strings.xml
Implemented functionality to create 2 different QR codes (check in and event details). Only visible to the user who has created the event.
> Creating QR codes

- app/src/main/java/com/example/circleapp/FirebaseManager.java
- app/src/main/java/com/example/circleapp/QRCode/ScanQRActivity.java
Scanning an event details QR code now shows the event details for that event. Also fixed some back button issues.
Still have to add error checking for if the eventID is not in firebase
> Event Details QR

- app/build.gradle.kts
- app/javadocs/com/example/circleapp/BaseObjects/Event.html
- app/src/main/java/com/example/circleapp/BaseObjects/Event.java
- app/src/main/java/com/example/circleapp/EventDisplay/CreateEventActivity.java
- app/src/main/java/com/example/circleapp/EventDisplay/EventDetailsActivity.java
- app/src/main/java/com/example/circleapp/FirebaseManager.java
- app/src/main/java/com/example/circleapp/ImageManager.java
- app/src/main/res/layout/activity_create_event.xml
- app/src/test/java/com/example/circleapp/EventUnitTest.java
Can now add and view event posters. Pictures can be selected from the user device and they are also uploaded to firebase storage when the event is created.
There is no default image set so for now you have to click the blank space beneath "Guests Allowed" when creating an event.
> Event Posters

- app/src/main/java/com/example/circleapp/EventDisplay/EventDetailsActivity.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/values/strings.xml
Only 1 generate qr button now with an alert dialog box to choose qrtype
> Generate QR Button

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/circleapp/BaseObjects/Event.java
- app/src/main/java/com/example/circleapp/EventDisplay/EventDetailsActivity.java
- app/src/main/java/com/example/circleapp/FirebaseManager.java
- app/src/main/java/com/example/circleapp/QRCode/GenerateQRActivity.java
- app/src/main/java/com/example/circleapp/QRCode/ReuseQRActivity.java
- app/src/main/java/com/example/circleapp/QRCode/ScanQRActivity.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/values/strings.xml
Some basic functionality to reuse a code. You can scan a code you want to reuse but that scanned code does not fully work for checkins yet.
> Reuse QR Code

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/circleapp/BaseObjects/Event.java
- app/src/main/java/com/example/circleapp/FirebaseManager.java
- app/src/main/java/com/example/circleapp/QRCode/GenerateQRActivity.java
- app/src/main/java/com/example/circleapp/QRCode/ReuseQRActivity.java
- app/src/main/java/com/example/circleapp/QRCode/ScanQRActivity.java
Reusing a QR code for check in should work as expected now. There is some error checking in place to ensure the resued qr code is not for an existing event, however more may need to be added.
> Reuse QR Code V2

- app/src/main/java/com/example/circleapp/FirebaseManager.java
Added subcollection that tracks every time a user checks in along with a timestamp.
> Number of check-ins

- app/src/main/java/com/example/circleapp/EventDisplay/CreateEventActivity.java
- app/src/main/java/com/example/circleapp/Firebase/ImageManager.java
- app/src/main/res/values/strings.xml
Can now create an event without uploading event poster. A default poster will be set (located in firebase storage)
> Default Event Poster

- app/src/main/java/com/example/circleapp/BaseObjects/Announcement.java
- app/src/main/java/com/example/circleapp/EventDisplay/AnnouncementAdapter.java
- app/src/main/java/com/example/circleapp/EventDisplay/EventDetailsActivity.java
- app/src/main/java/com/example/circleapp/Firebase/FirebaseManager.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/layout/announcement_item.xml
What I have so far for Announcement implementation, not yet complete.
> What I have so far for Announcement implementation, not yet complete.

- app/src/main/java/com/example/circleapp/BaseObjects/Announcement.java
- app/src/main/java/com/example/circleapp/EventDisplay/EventDetailsActivity.java
- app/src/main/java/com/example/circleapp/Firebase/FirebaseManager.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/layout/dialog_add_announcement.xml
Implementation not fully complete yet
> Announcements can now be added to events

- app/src/main/java/com/example/circleapp/EventDisplay/EventDetailsActivity.java
- app/src/main/java/com/example/circleapp/Firebase/FirebaseManager.java
- app/src/main/res/layout/activity_event_details.xml
Announcement interaction roles set up, click announcement to delete
> Deletion of announcements, click item to delete

- app/src/main/java/com/example/circleapp/Admin/AdminBrowseProfilesFragment.java
- app/src/main/java/com/example/circleapp/UserDisplay/CheckedInUsersFragment.java
- app/src/main/java/com/example/circleapp/UserDisplay/GuestlistActivity.java
- app/src/main/java/com/example/circleapp/UserDisplay/RegisteredUsersFragment.java
- app/src/main/res/layouts/events/layout/activity_event_details.xml
- app/src/main/res/layouts/events/layout/activity_guestlist.xml
- app/src/main/res/layouts/events/layout/fragment_checked_in_users.xml
- app/src/main/res/layouts/events/layout/fragment_guestlist_admin.xml
- app/src/main/res/layouts/events/layout/fragment_registered_users.xml
Guestliest is now a tabbed view with registered and checked in users
> Checked in Users

- app/src/main/java/com/example/circleapp/UserDisplay/CheckedInUsersFragment.java
Guestlist now displayes checked in users properly
> Fixed Checked in List

- app/src/main/java/com/example/circleapp/Admin/AdminBrowseProfilesFragment.java
- app/src/main/java/com/example/circleapp/BaseObjects/Attendee.java
- app/src/main/java/com/example/circleapp/Firebase/FirebaseManager.java
- app/src/main/java/com/example/circleapp/UserDisplay/AttendeeAdapter.java
- app/src/main/java/com/example/circleapp/UserDisplay/CheckedInUsersFragment.java
- app/src/main/java/com/example/circleapp/UserDisplay/RegisteredUsersFragment.java
- app/src/main/res/layouts/attendees/layout/attendee_item.xml
- app/src/main/res/layouts/events/layout/fragment_checked_in_users.xml
- app/src/main/res/layouts/events/layout/fragment_registered_users.xml
Can now view number of times a user has checked in in the Checked-In tab of the guestlist. Also changed some UI elements
> Check In Count

- app/src/main/java/com/example/circleapp/EventDisplay/EventDetailsActivity.java
- app/src/main/java/com/example/circleapp/Firebase/FirebaseManager.java
- app/src/main/res/layouts/events/layout/activity_event_details.xml
> Real-time attendee count

- app/src/main/java/com/example/circleapp/EventDisplay/AttendingEventsDetailsActivity.java
- app/src/main/java/com/example/circleapp/EventDisplay/BrowseEventsDetailsActivity.java
- app/src/main/java/com/example/circleapp/EventDisplay/RegisteredEventsFragment.java
- app/src/main/java/com/example/circleapp/Firebase/FirebaseManager.java
- app/src/main/res/layout/activity_attending_events_details.xml
Added functionality to unregister from an event from the BrowseEventsFragment and RegisteredEventsFragment
> Unregister from event

- app/src/main/java/com/example/circleapp/QRCode/GenerateQRActivity.java
- app/src/main/res/layouts/qr_code/layout/activity_generate_qr.xml
- app/src/main/res/values/strings.xml
Added QRtype text. Removed share button from check in qr code
> QR UI Improvements

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/circleapp/EventDisplay/AttendingEventsDetailsActivity.java
- app/src/main/java/com/example/circleapp/EventDisplay/BrowseEventsDetailsActivity.java
- app/src/main/java/com/example/circleapp/EventDisplay/EventDetailsActivity.java
- app/src/main/java/com/example/circleapp/EventDisplay/FullScreenImageActivity.java
- app/src/main/res/anim/fade_in.xml
- app/src/main/res/anim/fade_out.xml
- app/src/main/res/anim/zoom_in.xml
- app/src/main/res/anim/zoom_out.xml
- app/src/main/res/layouts/events/layout/activity_full_screen_image.xml
- app/src/main/res/values/themes.xml
Clicking event posters now makes them bigger. Added some animations as well.
> Click Event Poster

- app/src/main/java/com/example/circleapp/Profile/ProfileFragment.java
- app/src/main/java/com/example/circleapp/QRCode/ScanQRActivity.java
- app/src/main/res/layouts/attendees/layout/fragment_profile.xml
Added individual methods for each function. Added functionality to start temp user activity when checking in without a profile. Corrected the event details scan to launch BrowseEventDetails instead of EventDetails
> Refactor ScanQRActivity
